### ISSUE TITLE
Dropdown stopped opening when adding Toast component

### ISSUE THREAD

**Issue by softsolutionsau** [svierk/angular-bootstrap-toast-service#55]
Hello Sebastiano,

Thank you for putting this project together, it has helped me a lot. 

I do have one issue however. When I add the Toast component, all my existing dropdown (Bootstrap 5) elements stop opening. I have been able to isolate it to the Toast component (not Toaster).

I forked your code and added a drop down and it works just fine, so it is something with my code.

Any ideas why this may be happening?

Thanks!
Shai

**Comment by svierk** [comment]
Hi Shai, could you please elaborate a bit more? Without additional details about your project setup, it's really hard to make a guess.

**Comment by softsolutionsau** [comment]
Yes, of course. Appreciate the help!

Before using your technique I was using Bootstrap (css/js).

`agnular.json`
 ```
...
],
            "styles": [
              "src/assets/styles/styles.scss",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/assets/styles/jquery.dataTables.min.css",
              "src/assets/styles/select.dataTables.css",
              "src/assets/styles/font-awesome.min.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
              "node_modules/datatables.net/js/jquery.dataTables.js",
              "node_modules/jszip/dist/jszip.js",
              "node_modules/datatables.net-buttons/js/dataTables.buttons.js",
              "node_modules/datatables.net-buttons/js/buttons.colVis.js",
              "node_modules/datatables.net-buttons/js/buttons.flash.js",
              "node_modules/datatables.net-buttons/js/buttons.html5.js",
              "node_modules/datatables.net-buttons/js/buttons.print.js",
              "node_modules/datatables.net-select/js/dataTables.select.js"
            ]
          },
...
```

To get ToastComponent to work, I had to install types (npm @types/bootstrap). This allowed me to import 
`import {Toast} from 'bootstrap'`

When I comment out the import (and corresponding references to the Toast type), my drop-downs start to open again as normal.

**Comment by svierk** [comment]
Thanks for sharing more information. I think the way Bootstrap is currently imported in your project is not ideal and this why it collides with my approach. Please take a look at my project's [styles.scss](https://github.com/svierk/angular-bootstrap-toast-service/blob/main/src/styles.scss) where I import all the Bootstrap dependencies I need for my project. 

The package [@types/bootstrap](https://www.npmjs.com/package/@types/bootstrap) additionally just provides type definitions for Bootstrap to have a convenient way to use them in ts code.

**Comment by softsolutionsau** [comment]
Appreciate the guidance! :)
